config/routes.rb
Rails.application.routes.draw do
  root to: 'cocktails#index'
  resources :cocktails, only: [:show, :new, :create] do
    resources :doses, only: [:create]
    resources :reviews, only: [:create]
  end
  resources :doses, only: [:destroy]
  resources :reviews, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  has_many :doses, dependent: :destroy
  has_many :ingredients,
           through: :doses
  has_many :reviews, dependent: :destroy
  validates :name, presence: true, uniqueness: true
  validates :photo, presence: true
  validates :description, presence: true
  mount_uploader :photo, PhotoUploader
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :ingredient
  belongs_to :cocktail
  validates :description, presence: true
  validates :ingredient_id, presence: true
  validates :cocktail_id, presence: true
  validates :ingredient_id, uniqueness: { scope: :cocktail_id }
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :doses
  has_many :cocktails,
           through: :doses
  validates :name, presence: true, uniqueness: true
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :cocktail
  validates :stars, presence: true, numericality: { only_integer: true }
  validates :description, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  def index
    @search_term = params[:q]
    if @search_term.nil?
      @cocktails = Cocktail.all
    else
      regex = Regexp.new(@search_term, "i")
      @cocktails = Cocktail.select { |cocktail| cocktail.name.match(regex) }
    end
  end

  def show
    @cocktail = Cocktail.find(params[:id])
    @review = Review.new
    @dose = Dose.new
  end

  def new
    @cocktail = Cocktail.new
  end

  def create
    @cocktail = Cocktail.new(cocktail_params)
    if @cocktail.save
      redirect_to cocktail_path(@cocktail)
    else
      render 'new'
    end
  end

  def cocktail_params
    params.require(:cocktail).permit(:name, :photo, :description)
  end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController
  def new
    @dose = Dose.new
    @cocktail = Cocktail.find(params[:cocktail_id])
  end

  def create
    @dose = Dose.new(dose_params)
    @dose.cocktail = Cocktail.find(params[:cocktail_id])
    @dose.save
    redirect_to cocktail_path(@dose.cocktail)
  end

  def dose_params
    params.require(:dose).permit(:description, :ingredient_id)
  end

  def destroy
    @dose = Dose.find(params[:id])
    @cocktail = @dose.cocktail
    if @dose.destroy
      redirect_to cocktail_path(@cocktail)
    else
      render 'cocktails/new'
    end
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def create
    @review = Review.new(review_params)
    @cocktail = Cocktail.find(params[:cocktail_id])
    @review.cocktail = @cocktail
    if @review.save
      redirect_to cocktail_path(@cocktail)
    else
      render 'cocktails/show'
    end
  end

  def destroy
    @review = Review.find(params[:id])
    @review.destroy
    redirect_to cocktail_path(@review.cocktail)
  end

  def review_params
    params.require(:review).permit(:description, :stars)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/cocktails/index.html.erb
<div class="container my-5">
  <% if @search_term %>
    <h1>Search results for "<%= @search_term %>" (<%= @cocktails.length %> results)</h1>
  <% else %>
    <h1>All cocktails</h1>
  <% end %>
  <div class="row">
    <% @cocktails.each do |cocktail| %>
      <div class="col-12 col-sm-6 col-md-4">
        <%= link_to cocktail_path(cocktail), class: 'card-cocktail-link' do %>
          <div class="card-cocktail-content" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(<%= cl_image_path cocktail.photo, height: 300, width: 400, crop: :fill %>)">
            <h3>
                <%= cocktail.name %>
            </h3>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/cocktails/new.html.erb
<div class="container my-5">
  <h1>Add a cocktail</h1>

  <%= simple_form_for [@cocktail] do |f| %>
    <%= f.input :name %>
    <%= f.input :description %>
    <%= f.input :photo %>
    <%= f.input :photo_cache, as: :hidden %>
    <%= f.submit "Add Cocktail", class: "btn btn-primary" %>
  <% end %>
</div>

app/views/cocktails/show.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(<%= cl_image_path @cocktail.photo, crop: :fill %>);">
  <div class="container">
    <h1><%= @cocktail.name %></h1>
    <p><%= @cocktail.doses.length %> <%= @cocktail.doses.length == 1 ? "ingredient" : "ingredients" %></p>
  </div>
</div>
<div class="container mb-5">
  <div class="row">
    <div class="col-12 col-md-6">
      <div class="card-show-section">
        <h2>Description</h2>
        <%= @cocktail.description %>
      </div>
      <div class="card-show-section">
        <h2>Ingredients</h2>
        <ul class="list-group">
          <% @cocktail.doses.each do |dose| %>
            <li class="list-group-item d-flex justify-content-between">
              <p class="m-0">
                <strong><%= dose.ingredient.name %>:</strong> <%= dose.description %>
              </p>
              <%= link_to dose_path(dose), method: :delete do %>
                <i class="fas fa-trash-alt"></i>
              <% end %>
            </li>
          <% end %>
        </ul>

      </div>
      <div class="card-show-section">
        <h2>Add an ingredient</h2>
        <%= simple_form_for [@cocktail, @dose] do |f| %>
          <%= f.association :ingredient, input_html: { class: 'select2 form-control' } %>
          <%= f.input :description %>
          <%=  %>
          <%= f.submit "Add", class: "btn btn-primary" %>
        <% end %>
      </div>
    </div>
    <div class="col-12 col-md-6">
      <div class="card-show-section">
        <h2>Reviews</h2>
        <ul class="list-group">
          <% @cocktail.reviews.each do |review| %>
            <li class="list-group-item d-flex justify-content-between">
              <p class="m-0">
                <strong><%= review.description %></strong> (<%= review.stars %> stars)
              </p>
              <%= link_to review_path(review), method: :delete do %>
                <i class="fas fa-trash-alt"></i>
              <% end %>
            </li>
          <% end %>
        </ul>
      </div>
      <div class="card-show-section">
                <h2>Add an review</h2>
        <%= simple_form_for [@cocktail, @review] do |f| %>
          <%= f.input :stars, label: false, placeholder: 'Number of stars' %>
          <%= f.input :description, label: false, placeholder: 'Write something here'%>
          <%=  %>
          <%= f.submit "Add", class: "btn btn-primary" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cocktail Wizard</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "shared/header" %>
    <%= yield %>
    <%= render "shared/footer" %>
    <%= javascript_include_tag "application" %> <!-- from app/assets/javascripts/application.js -->
  <%= javascript_pack_tag "application" %>    <!-- from app/javascript/packs/application.js -->
  </body>
</html>

app/views/shared/_footer.html.erb
<footer class="p-5 bg-dark d-flex justify-content-center align-items-center">
  <p class="m-0 text-white">Made in London by Liam</p>

</footer>

app/views/shared/_header.html.erb
<header class="header">
  <%= link_to cocktails_path, class: 'text-decoration-none' do %>
    <h3 class="m-0 text-dark">Cocktail Wizard</h3>
  <% end %>
  <div class="navbar-right d-none d-md-flex align-items-center justify-content-between">
    <form class="form-inline d-inline-block" action="/cocktails">
      <div class="form-group">
        <input class="form-control" type="text" name="q" placeholder="Search for cocktails">
        <input class="ml-1 form-control btn btn-success" type="submit" value="Search">
      </div>
    </form>
    <%= link_to "Add Cocktail", new_cocktail_path, class:'btn btn-outline-primary d-inline-block ml-3' %>
  </div>
</header>